-- 初始化剩余表和种子数据
CREATE TABLE IF NOT EXISTS bid_project (id BIGINT PRIMARY KEY, name VARCHAR(200) NOT NULL, code VARCHAR(50) UNIQUE, type VARCHAR(50), amount DECIMAL(15,2), tenderer VARCHAR(200), contact_person VARCHAR(100), contact_phone VARCHAR(20), deadline TIMESTAMP, status VARCHAR(20) DEFAULT E'DRAFT', description TEXT, create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP, update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP, create_by BIGINT, update_by BIGINT, version INTEGER DEFAULT 0, deleted INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS bid_material (id BIGINT PRIMARY KEY, name VARCHAR(200) NOT NULL, type VARCHAR(50), project_id BIGINT, file_path VARCHAR(500), file_size BIGINT, file_type VARCHAR(50), upload_user_id BIGINT, status VARCHAR(20) DEFAULT E'PENDING', remark VARCHAR(500), create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP, update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP, create_by BIGINT, update_by BIGINT, version INTEGER DEFAULT 0, deleted INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS bid_document (id BIGINT PRIMARY KEY, name VARCHAR(200) NOT NULL, type VARCHAR(50), project_id BIGINT, material_id BIGINT, file_path VARCHAR(500), file_size BIGINT, content TEXT, parse_status VARCHAR(20) DEFAULT E'PENDING', analysis_result TEXT, status VARCHAR(20) DEFAULT E'ACTIVE', create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP, update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP, create_by BIGINT, update_by BIGINT, version INTEGER DEFAULT 0, deleted INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS bid_template (id BIGINT PRIMARY KEY, name VARCHAR(200) NOT NULL, code VARCHAR(50) UNIQUE, category VARCHAR(50), content TEXT, file_path VARCHAR(500), is_default INTEGER DEFAULT 0, status INTEGER DEFAULT 0, create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP, update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP, create_by BIGINT, update_by BIGINT, version INTEGER DEFAULT 0, deleted INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS ai_task (id BIGINT PRIMARY KEY, task_type VARCHAR(50) NOT NULL, target_type VARCHAR(50), target_id BIGINT, input_data TEXT, output_data TEXT, status VARCHAR(20) DEFAULT E'PENDING', error_message VARCHAR(500), start_time TIMESTAMP, end_time TIMESTAMP, cost_time BIGINT, create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP, update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP, create_by BIGINT, update_by BIGINT, version INTEGER DEFAULT 0, deleted INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS sys_operation_log (id BIGINT PRIMARY KEY, module VARCHAR(50), business_type VARCHAR(20), method VARCHAR(200), request_method VARCHAR(10), request_url VARCHAR(500), request_params TEXT, response_data TEXT, user_id BIGINT, username VARCHAR(50), ip VARCHAR(50), user_agent VARCHAR(500), cost_time BIGINT, status INTEGER DEFAULT 0, error_message VARCHAR(500), create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

-- 插入示例项目
INSERT INTO bid_project (id, name, code, type, amount, tenderer, contact_person, contact_phone, status, description, create_time, update_time, deleted) VALUES (1, E'智慧城市数据治理平台建设项目', E'BID-2024-001', E'智慧城市', 5000000.00, E'某市政府信息中心', E'张主任', E'13800138000', E'IN_PROGRESS', E'建设智慧城市数据治理平台，实现城市数据统一管理', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0) ON CONFLICT (code) DO NOTHING;

-- 插入示例素材
INSERT INTO bid_material (id, name, type, project_id, file_path, file_size, file_type, upload_user_id, status, remark, create_time, update_time, deleted) VALUES (1, E'智慧城市技术方案V1.0', E'technical', 1, E'/uploads/bid-001-tech.docx', 1048576, E'docx', 1, E'APPROVED', E'智慧城市技术方案初稿', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0) ON CONFLICT DO NOTHING;

-- 插入示例模板
INSERT INTO bid_template (id, name, code, category, content, is_default, status, create_time, deleted) VALUES (1, E'智慧城市技术标模板', E'TECH-STANDARD', E'技术标', E'智慧城市技术标标准模板内容...', 1, 0, CURRENT_TIMESTAMP, 0), (2, E'商务标标准模板', E'BIZ-STANDARD', E'商务标', E'商务标标准模板内容...', 0, 0, CURRENT_TIMESTAMP, 0) ON CONFLICT (code) DO NOTHING;
